# Generated by Django 2.2.7 on 2021-05-16 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('members', models.CharField(max_length=255, verbose_name='Membros')),
                ('published_at', models.DateField(verbose_name='Data de publicação')),
                ('thumbnail', models.URLField()),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodios',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('audio/x-m4a', 'x-m4a'), ('audio/mp3', 'mp3')], max_length=25, verbose_name='Tipo')),
                ('duration', models.IntegerField(verbose_name='Duração')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='episodes.Episode')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
